# Generated by Django 3.0.1 on 2024-01-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_edit_del_date',
            name='time',
        ),
        migrations.AddField(
            model_name='add_edit_del_date',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='add_edit_del_date',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
