# Generated by Django 3.0.1 on 2024-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_auto_20240120_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edit_del_date',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
