# Generated by Django 3.0.1 on 2024-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_auto_20240120_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_edit_del_date',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
